GET http://localhost:3000/api/resumes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSGFzYW4iLCJ1c2VySWQiOjEsImlhdCI6MTc3MTQzOTMzN30.sTOB9lAFKraexlG-KVCyMaiZtfUv7WsgwDvxd7_ldY8

